# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GphotosUploaderCli < Formula
  desc "Mass upload media folders to your Google Photos account(s)"
  homepage "https://github.com/gphotosuploader/gphotos-uploader-cli"
  version "3.5.1-alpha"

  on_macos do
    url "https://github.com/gphotosuploader/gphotos-uploader-cli/releases/download/v3.5.1-alpha/gphotos-uploader-cli_3.5.1-alpha_darwin_amd64.tar.gz"
    sha256 "b8d6eca9ed1489ff9faa3c8f895e94354c61a84cfb9895e5c7ef9f88f7ed35da"

    def install
      bin.install "gphotos-uploader-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GphotosUploaderCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gphotosuploader/gphotos-uploader-cli/releases/download/v3.5.1-alpha/gphotos-uploader-cli_3.5.1-alpha_linux_amd64.tar.gz"
      sha256 "5a2d200191688c0ee70fb59a7995c15e53339bdabc757c14f59c0c201b3bac48"

      def install
        bin.install "gphotos-uploader-cli"
      end
    end
  end

  test do
    system "#{bin}/gphotos-uploader-cli --help"
  end
end
