# This file was generated by GoReleaser. DO NOT EDIT.
class GphotosUploaderCli < Formula
  desc "Mass upload media folders to your Google Photos account(s)"
  homepage "https://github.com/gphotosuploader/gphotos-uploader-cli"
  version "0.8.1-pre"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gphotosuploader/gphotos-uploader-cli/releases/download/v0.8.1-pre/gphotos-uploader-cli_0.8.1-pre_darwin_amd64.tar.gz"
    sha256 "d1775b166930793362451081e08f1c7817aa523923dccdf0f5ac768ab4e4b6b0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gphotosuploader/gphotos-uploader-cli/releases/download/v0.8.1-pre/gphotos-uploader-cli_0.8.1-pre_linux_amd64.tar.gz"
      sha256 "e4f285e2d128669dfec6db2e1e0475558a1cea1117a455947a8dedc790bccd1b"
    end
  end

  def install
    bin.install "gphotos-uploader-cli"
  end

  test do
    system "#{bin}/gphotos-uploader-cli --help"
  end
end
