# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GphotosUploaderCli < Formula
  desc "Mass upload media folders to your Google Photos account(s)"
  homepage "https://github.com/gphotosuploader/gphotos-uploader-cli"
  version "3.4.0"

  on_macos do
    url "https://github.com/gphotosuploader/gphotos-uploader-cli/releases/download/v3.4.0/gphotos-uploader-cli_3.4.0_darwin_amd64.tar.gz"
    sha256 "19f7cfd584418d53072cf4036042f26e4ca8eee0f22238a7723d083b89111437"

    def install
      bin.install "gphotos-uploader-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GphotosUploaderCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gphotosuploader/gphotos-uploader-cli/releases/download/v3.4.0/gphotos-uploader-cli_3.4.0_linux_amd64.tar.gz"
      sha256 "654a9a3fda9b9d132b4d70d8fed5e9aa5b81534785c494264978c2fa4572b313"

      def install
        bin.install "gphotos-uploader-cli"
      end
    end
  end

  test do
    system "#{bin}/gphotos-uploader-cli --help"
  end
end
